let a = {
    object_kind: "merge_request",
    event_type: "merge_request",
    user: {
        id: 6457388,
        name: "Ярослав Дмитриев",
        username: "webdev1232",
        avatar_url:
            "https://secure.gravatar.com/avatar/6c3bbf640ae10de3723419253d199a0c828edfd026715eea72bbc3ea3e9f132b?s=80&d=identicon",
        email: "[REDACTED]",
    },
    project: {
        id: 67254182,
        name: "test_bot",
        description: null,
        web_url: "https://gitlab.com/webdev1232/test_bot",
        avatar_url: null,
        git_ssh_url: "git@gitlab.com:webdev1232/test_bot.git",
        git_http_url: "https://gitlab.com/webdev1232/test_bot.git",
        namespace: "Ярослав Дмитриев",
        visibility_level: 0,
        path_with_namespace: "webdev1232/test_bot",
        default_branch: "master",
        ci_config_path: "",
        homepage: "https://gitlab.com/webdev1232/test_bot",
        url: "git@gitlab.com:webdev1232/test_bot.git",
        ssh_url: "git@gitlab.com:webdev1232/test_bot.git",
        http_url: "https://gitlab.com/webdev1232/test_bot.git",
    },
    object_attributes: {
        assignee_id: null,
        author_id: 6457388,
        created_at: "2025-06-14 11:47:32 UTC",
        description: "test",
        draft: false,
        head_pipeline_id: null,
        id: 391117528,
        iid: 6,
        last_edited_at: null,
        last_edited_by_id: null,
        merge_commit_sha: null,
        merge_error: null,
        merge_params: { force_remove_source_branch: "1" },
        merge_status: "checking",
        merge_user_id: null,
        merge_when_pipeline_succeeds: false,
        milestone_id: null,
        source_branch: "feature2",
        source_project_id: 67254182,
        state_id: 1,
        target_branch: "master",
        target_project_id: 67254182,
        time_estimate: 0,
        title: "Feature2",
        updated_at: "2025-06-14 11:47:35 UTC",
        updated_by_id: null,
        prepared_at: "2025-06-14 11:47:35 UTC",
        assignee_ids: [],
        blocking_discussions_resolved: true,
        detailed_merge_status: "checking",
        first_contribution: true,
        human_time_change: null,
        human_time_estimate: null,
        human_total_time_spent: null,
        labels: [],
        last_commit: {
            id: "e5ae61bdefac93b76be12f861c156e56b409a1f9",
            message: "init\n",
            title: "init",
            timestamp: "2025-02-26T23:03:55+03:00",
            url: "https://gitlab.com/webdev1232/test_bot/-/commit/e5ae61bdefac93b76be12f861c156e56b409a1f9",
            author: [Object],
        },
        reviewer_ids: [],
        source: {
            id: 67254182,
            name: "test_bot",
            description: null,
            web_url: "https://gitlab.com/webdev1232/test_bot",
            avatar_url: null,
            git_ssh_url: "git@gitlab.com:webdev1232/test_bot.git",
            git_http_url: "https://gitlab.com/webdev1232/test_bot.git",
            namespace: "Ярослав Дмитриев",
            visibility_level: 0,
            path_with_namespace: "webdev1232/test_bot",
            default_branch: "master",
            ci_config_path: "",
            homepage: "https://gitlab.com/webdev1232/test_bot",
            url: "git@gitlab.com:webdev1232/test_bot.git",
            ssh_url: "git@gitlab.com:webdev1232/test_bot.git",
            http_url: "https://gitlab.com/webdev1232/test_bot.git",
        },
        state: "opened",
        target: {
            id: 67254182,
            name: "test_bot",
            description: null,
            web_url: "https://gitlab.com/webdev1232/test_bot",
            avatar_url: null,
            git_ssh_url: "git@gitlab.com:webdev1232/test_bot.git",
            git_http_url: "https://gitlab.com/webdev1232/test_bot.git",
            namespace: "Ярослав Дмитриев",
            visibility_level: 0,
            path_with_namespace: "webdev1232/test_bot",
            default_branch: "master",
            ci_config_path: "",
            homepage: "https://gitlab.com/webdev1232/test_bot",
            url: "git@gitlab.com:webdev1232/test_bot.git",
            ssh_url: "git@gitlab.com:webdev1232/test_bot.git",
            http_url: "https://gitlab.com/webdev1232/test_bot.git",
        },
        time_change: 0,
        total_time_spent: 0,
        url: "https://gitlab.com/webdev1232/test_bot/-/merge_requests/6",
        work_in_progress: false,
        approval_rules: [],
        action: "open",
    },
    labels: [],
    changes: {
        merge_status: { previous: "preparing", current: "checking" },
        updated_at: {
            previous: "2025-06-14 11:47:32 UTC",
            current: "2025-06-14 11:47:35 UTC",
        },
        prepared_at: { previous: null, current: "2025-06-14 11:47:35 UTC" },
    },
    repository: {
        name: "test_bot",
        url: "git@gitlab.com:webdev1232/test_bot.git",
        description: null,
        homepage: "https://gitlab.com/webdev1232/test_bot",
    },
};
